poegrass/urls.py
from django.contrib import admin
from django.urls import path,include
import accounts.views


urlpatterns = [
    path('@<slug:account_id>/',accounts.views.ProfileView.as_view(),name="profile"),
    path('accounts/',include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('',include('utakais.urls')),
]

utakais/urls.py
from . import views
from django.contrib import admin
from django.http import HttpResponseNotFound
from django.urls import path

app_name = "utakais"

urlpatterns = [
    path('events/<int:pk>/admin/', views.EventAdminView.as_view(), name="event_admin"),
    path('events/<int:pk>/download/<str:file_type>/',views.download_eisou_file,name="download_eisou_file"),
    path('events/<int:pk>/execute_method/<str:method_name>/', views.execute_method, {'app_name': 'utakais', 'model_name': 'Event'}, name='execute_method'),
    path('events/<int:pk>/',views.change_event_view,name="event_detail"),
    path('events/create/',views.EventCreateView.as_view(),name="event_create"),
#    path('tankas/<int:pk>/edit',views.TankaEditView.as_view(),name="tanka_edit"),
    path('tankas/<int:pk>/',views.TankaDetailView.as_view(),name="tanka_detail"),
#    path('tankas/create/',views.TankaCreateView.as_view(),name="tanka_create"),
#    path('tankas/',views.TankaIndexView.as_view(),name="tanka_index"),
    path('',views.EventIndexView.as_view(),name="events_index"),
]

events/models.py
from django.db import models

# Create your models here.

utakais/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import Event, Participant, Tanka


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            "title",
            "start_time",
            "end_time",
            "location",
            "deadline",
            "ann_desc",
        ]
        widgets = {
            "title": forms.TextInput(
                attrs={"placeholder": "空欄の場合、開催日になります。"}
            ),
            "start_time": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "end_time": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "location": forms.TextInput(),
            "deadline": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "ann_desc": forms.Textarea(
                attrs={
                    "rows": 5,
                    "cols": 40,
                    "placeholder": "コメントを記入してください",
                }
            ),
        }


class TankaForm(forms.ModelForm):
    class Meta:
        model = Tanka
        fields = [
            "author",
            "content",
            "guest_author",
        ]

    def __init__(self, *args, author=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["author"].widget = forms.HiddenInput()

        if author and author.is_authenticated:
            # ログイン時は ログイン情報からauthorを設定し, guest_authorを非表示
            self.fields["author"].initial = author
            self.fields["guest_author"].widget = forms.HiddenInput()
            self.fields["guest_author"].required = False


class ParticipantForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = [
            "user",
            "guest_user",
            "guest_contact",
            "message",
        ]

    def __init__(self, *args, user=None, hide_guest_user=False, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["user"].widget = forms.HiddenInput()

        if user and user.is_authenticated:
            # ログイン時は ログイン情報からuserを設定し, guest_user, guest_contact を非表示
            self.fields["user"].initial = user
            self.fields["guest_user"].widget = forms.HiddenInput()
            self.fields["guest_contact"].widget = forms.HiddenInput()
            self.fields["guest_user"].required = False
            self.fields["guest_contact"].required = False

        if hide_guest_user == True:
            self.fields["guest_user"].widget = forms.HiddenInput()


class ParticipantInlineForm(forms.ModelForm):
    username = forms.CharField(
        label="名前",
        widget=forms.TextInput(
            attrs={
                "readonly": True,
            }
        ),
    )
    tanka_content = forms.CharField(
        label="短歌",
        widget=forms.TextInput(
            attrs={
                "readonly": True,
            }
        ),
    )

    class Meta:
        model = Participant
        fields = (
            "username",
            "tanka_content",
            "message",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if "instance" in kwargs and kwargs["instance"]:
            instance: Participant = kwargs["instance"]


            self.fields["username"].initial = instance.name
            self.fields["tanka_content"].initial = (
                instance.tanka.content if instance.tanka is not None else ""
            )
            self.fields["username"].required = False
            self.fields["tanka_content"].required = False


ParticipantFormSet = inlineformset_factory(
    Event,  # 親モデル
    Participant,  # 子モデル
    form=ParticipantInlineForm,
    # fields=[],  # 編集可能なフィールド
    extra=0,  # 新規追加の空フォーム数
    can_delete=True,  # 削除チェックボックスを有効にする
)

utakais/views.py
from pathlib import Path

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.core.files.storage import default_storage
from django.http import FileResponse, Http404, HttpResponseNotFound
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (
    CreateView,
    DetailView,
    FormView,
    ListView,
)
from django.views.generic.edit import UpdateView

from .forms import EventForm, ParticipantForm, ParticipantFormSet, TankaForm
from .models import Event, Participant, Tanka


class EventIndexView(ListView):
    model = Event
    template_name = "utakais/events/index.html"
    context_object_name = "events"

    def get_queryset(self):
        user = self.request.user
        if user.is_authenticated and user.is_member:
            queryset = Event.objects.filter(ann_status__in=["public", "limited"])
        else:
            queryset = Event.objects.filter(ann_status="public")
        return queryset


class EventCreateView(CreateView):
    model = Event
    template_name = "utakais/events/create.html"
    form_class = EventForm

    def form_valid(self, form):
        event = form.save(commit=False)
        event.organizer = self.request.user
        event.save()
        return super().form_valid(form)

    success_url = reverse_lazy("utakais:events_index")


def change_event_view(request, pk):
    """
    歌会の公開非公開などによって表示するビューを変える。
    告知公開前->何も表示しない
    告知公開中から締め切り前->短歌投稿フォーム(EventDetailView)
    締め切り後->締め切りましたor短歌一覧（EventOngoingView）
    記録公開後->記録用のビュー（EventRecordView）
    """
    event = get_object_or_404(Event, pk=pk)
    user = request.user
    if event.rec_is_public:
        return EventRecordView.as_view()(request, pk=pk)
    elif event.rec_is_limited:
        if user.is_authenticated and user.is_member:
            return EventRecordView.as_view()(request, pk=pk)
        else:
            return event_not_found(request)
    elif event.rec_is_private:
        if event.ann_is_public:
            if event.deadline > timezone.now():
                return EventDetailView.as_view()(request, pk=pk)
            else:
                return EventOngoingView.as_view()(request, pk=pk)
        elif event.ann_is_limited:
            if user.is_authenticated and user.is_member:
                if event.deadline > timezone.now():
                    return EventDetailView.as_view()(request, pk=pk)
                else:
                    return EventOngoingView.as_view()(request, pk=pk)
            else:
                return event_not_found
        elif event.ann_is_private:
            return event_not_found(request)


def event_not_found(request):
    return HttpResponseNotFound("<h1>歌会が見つかりません。</h1>")


class EventDetailView(FormView):
    template_name = "utakais/events/detail.html"
    form_class = ParticipantForm

    def form_invalid(self, form):
        tanka_form = TankaForm(self.request.POST)
        participant_form = ParticipantForm(self.request.POST)
        context = self.get_context_data(
            tanka_form=tanka_form,
            participant_form=participant_form,
        )
        return self.render_to_response(context)

    def form_valid(self, form):
        tanka_form = TankaForm(self.request.POST)
        participant_form = ParticipantForm(self.request.POST)
        user = self.request.user
        event = get_object_or_404(Event, pk=self.kwargs["pk"])

        if "delete" in self.request.POST:
            try:
                participant = Participant.objects.get(user=user, event=event)
                participant.delete()
                if participant.tanka:
                    participant.tanka.delete()
                messages.success(self.request, "参加を取り消しました。")
                return redirect("utakais:events_index")
            except Participant.DoesNotExist:
                messages.error(self.request, "参加の取り消しに失敗しました。")
                return self.request.path

        if tanka_form.is_valid() and participant_form.is_valid():
            empty = ""  # 詠草提出しない場合の詠草入力欄

            # ---tankaを保存---
            if not tanka_form.cleaned_data["content"] == empty:
                tanka = tanka_form.save(commit=False)
                tanka.author = user if user.is_authenticated else None
                tanka.save()
            else:
                tanka = None

            # ---Participantを保存---
            if user.is_authenticated:
                participant, created = Participant.objects.get_or_create(
                    user=user,
                    event=event,
                )

                if not created:
                    messages.success(self.request, "再提出しました。")
                    if participant.tanka:
                        participant.tanka.delete()
                else:
                    messages.success(self.request, "提出しました。")

                participant.message = participant_form.cleaned_data["message"]

            else:
                participant = participant_form.save(commit=False)
                participant.event = event
                participant.guest_user = tanka_form.cleaned_data["guest_author"]
                messages.success(self.request, "提出しました。")

            participant.tanka = tanka
            participant.save()

        else:
            messages.error(self.request, "提出に失敗しました。")
            return self.render_to_response(
                self.get_context_data(
                    tanka_form=tanka_form, participant_form=participant_form
                )
            )

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        tanka_formとparticipant_formを設定
        ParticipantFormをログイン状態によって動的に変化させるため,userを渡す
        """
        context = super().get_context_data(**kwargs)
        user = self.request.user
        event = get_object_or_404(Event, pk=self.kwargs["pk"])
        context["event"] = event
        context["joined"] = False

        if "tanka_form" in kwargs and "participant_form" in kwargs:
            context["tanka_form"] = kwargs["tanka_form"]
            context["participant_form"] = kwargs["participant_form"]
            context["participant_form"].fields[
                "guest_user"
            ].widget = forms.HiddenInput()
            return context

        if user.is_authenticated:
            # ---tanka_formの初期値を設定---
            tanka_initial = {}
            try:
                participant = Participant.objects.get(user=user, event=event)
                context["joined"] = True
                if participant.tanka:
                    tanka_initial["content"] = participant.tanka.content
            except Participant.DoesNotExist:
                pass
            context["tanka_form"] = TankaForm(initial=tanka_initial, author=user)

            # ---participant_formの初期値,kwargsを設定---
            participant_initial = {}
            try:
                participant = Participant.objects.get(user=user, event=event)
                if participant.tanka:
                    participant_initial["message"] = participant.message
            except Participant.DoesNotExist:
                pass
            context["participant_form"] = ParticipantForm(
                initial=participant_initial,
                user=user,
            )

        else:
            context["tanka_form"] = TankaForm()
            context["participant_form"] = ParticipantForm(
                initial={
                    "guest_user": "未入力"
                },  # validationerrorを起こさないために仮置きしている。
                hide_guest_user=True,
            )

        return context

    def get_success_url(self):
        success_url = self.request.path
        return success_url


class EventOngoingView(DetailView):
    model = Event
    template_name = "utakais/events/ongoing.html"

    def get(request, *args, **kwargs):
        event = get_object_or_404(Event, pk=kwargs["pk"])

        # サニタイズ（ファイル名の安全な形式への変換）された名前
        file_name = default_storage.get_valid_name(event.title)

        doc_path = settings.MEDIA_ROOT / Path(
            f"events/{event.pk}/{file_name}_ver{event.eisou_number}.docx"
        )
        pdf_path = settings.MEDIA_ROOT / Path(
            f"events/{event.pk}/{file_name}_ver{event.eisou_number}.pdf"
        )
        if doc_path.is_file() and pdf_path.is_file():
            pass
        else:
            event.generate_files()
        return super().get(request, *args, **kwargs)


class EventRecordView(DetailView):
    model = Event
    template_name = "utakais/events/record.html"

    def get_context_data(self, **kwargs):
        print("ここ")
        context = super().get_context_data(**kwargs)
        context['public_participants'] = Participant.objects.filter(event=self.object, tanka__status="public")
        context['limited_participants'] = Participant.objects.filter(event=self.object, tanka__status="limited")
        return context


class EventAdminView(UpdateView):
    model = Event
    fields = [
        "title",
        "start_time",
        "end_time",
        "location",
        "deadline",
        "ann_status",
        "ann_desc",
        "rec_status",
        "rec_desc",
        "eisou_doc",
        "eisou_pdf",
    ]
    template_name = "utakais/events/admin.html"

    def get_success_url(self):
        return self.request.path

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        event = self.get_object()
        context["event_form"] = self.get_form()

        if self.request.POST:
            context["participant_formset"] = ParticipantFormSet(
                self.request.POST, instance=event
            )
        else:
            context["participant_formset"] = ParticipantFormSet(instance=event)

        return context

    def form_valid(self, form):
        context = self.get_context_data()

templates/utakais/events/admin.html
{% extends 'base.html' %}

{% block head_title %}
歌会管理
{% endblock %}
{% block body_title %}
    <h1>
        歌会管理
    </h1>
{% endblock %}
{% block content %}
    <div>
        <a href="{% url 'utakais:event_detail' pk=event.pk %}">戻る</a>
    </div>
    <form method="post">
        {% csrf_token %}
        {{ event_form.as_p }}

        <h3>参加者情報</h3>
        {{ participant_formset.management_form }}

        <table border="1">
            {{ formset.non_form_errors.as_ul }}
            <table id="formset" class="form">
            {% for form in participant_formset.forms %}
              {% if forloop.first %}
              <thead><tr>
                {% for field in form.visible_fields %}
                <th>{{ field.label|capfirst }}</th>
                {% endfor %}
              </tr></thead>
              {% endif %}
              <tr class="{% cycle row1 row2 %}">
              {% for field in form.visible_fields %}
                <td>
                {# Include the hidden fields in the form #}
                {% if forloop.first %}
                  {% for hidden in form.hidden_fields %}
                  {{ hidden }}
                  {% endfor %}
                {% endif %}
                  {{ field.errors.as_ul }}
                  {{ field }}
                </td>
              {% endfor %}
              </tr>
            {% endfor %}
            </table>

        <!-- {% for form in participant_formset %}
            <tr>
                <td>
                    <p>参加者:{{ form.instance.name }}</p>
                    {% if not form.instance.user %}
                        <p>連絡先: {{ form.instance.guest_contact }}</p>
                    {% endif %}
                </td>
                <td>
                    <p>{{ form.instance.tanka }}</p>
                </td>
                <td>
                    削除{{ form.DELETE }}
                </td>
            </tr>
        {% endfor %} -->
        </table>
        <div>
            <a href="{% url 'utakais:execute_method'
                app_name='utakais'
                model_name='Event'
                pk=event.pk
                method_name='generate_files'
                %}">
                {% if event.eisou_number == 0 %}
                    詠草一覧を生成
                {% else %}
                    詠草一覧を再生成
                {% endif %}
            </a>
        </div>
        <button type="submit">更新</button>
    </form>
{% endblock %}

templates/utakais/events/create.html
{% extends 'base.html' %}

{% block head_title %}
歌会作成
{% endblock %}
{% block body_title %}
    <h1>
        歌会作成
    </h1>
{% endblock %}
{% block content %}
<div>
    <br>
    <form method="POST">
      {% csrf_token %}
      <div class="alert alert-danger">
          {{ form.non_field_errors }}
      </div>
      {% for field in form %}
      {{ field.label }}
      {{ field }}
      <div class="alert alert-danger">
          {{ field.errors }}
      </div>
      <br>
      {% endfor %}
      <div class="mt-3">
        <button type="submit" class="btn btn-primary">作成</button>
        <a href="{% url 'utakais:events_index' %}" class="btn btn-secondary">戻る</a>
      </div>
    </form>
</div>   
{% endblock %}

templates/utakais/events/detail.html
{% extends 'base.html' %}

{% block head_title %}
    <title>歌会詳細</title>
{% endblock %}

{% block body_title %}
    <h1>{{ event.title }}</h1>
{% endblock %}

{% block content %}
    {% if user.is_authenticated and event.organizer and user == event.organizer %}
    <div>
        <a href="{% url 'utakais:event_admin' pk=event.pk %}">歌会管理へ</a>
    </div>
    {% endif %}
    <div>
        司会者：{{ event.organizer.name }}<br>
        開始日時：{{ event.start_time }}<br>
        場所：{{ event.location }}<br>
        詠草提出締切：{{ event.deadline }}<br>
        コメント：{{ event.ann_desc }}
    </div>
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ tanka_form.as_p }}
            {{ participant_form.as_p }}
            {% if joined %}
                <p>参加表明済み。再提出で詠草を修正できます。</p>
            {% endif %}
            <button type="submit">提出</button>
            {% if joined %}
                <button type="submit" name="delete">参加取消</button>
            {% endif %}
        </form>
        <a href="{% url 'utakais:events_index' %}">戻る</a>
    </div>
{% endblock %}

templates/utakais/events/index.html
{% extends 'base.html' %}

{% block head_title %}
    歌会一覧
{% endblock %}
{% block body_title %}
    <h1>
        歌会一覧
    </h1>
{% endblock %}
{% block content %}
    {% if not user.is_authenticated or not user.is_member %}
        ゲストユーザーのため、公開の歌会のみ表示されています。<br>
    {% endif %}
    {% if events %} 
    <div>
        {% for event in events %}
            <a href="{% url 'utakais:event_detail' pk=event.pk %}">{{ event.title }}</a><br>
        {% endfor %}
    </div>
    {% else %}
        現在予定されている歌会はありません。
    {% endif %}
    {% if user.is_member %}
        <a href="{% url 'utakais:event_create' %}">歌会を作成</a><br>
    {% endif %}
{% endblock %}

templates/utakais/events/ongoing.html
{% extends 'base.html' %}

{% block head_title %}
    <title>歌会詳細</title>
{% endblock %}

{% block body_title %}
    {% if event %}
    <h1>{{ event.title }}</h1>
    {% else %}
    <h1>歌会が見つかりません。</h1>
    {% endif %}
{% endblock %}

{% block content %}
    {% if user.is_authenticated and event.organizer and user == event.organizer %}
    <div>
        <a href="{% url 'utakais:event_admin' pk=event.pk %}">歌会管理へ</a>
    </div>
    {% endif %}
    <div>
        司会者：{{ event.organizer.name }}<br>
        開始日時：{{ event.start_time }}<br>
        場所：{{ event.location }}<br>
        詠草提出締切：{{ event.deadline }}<br>
        コメント：{{ event.ann_desc }}
    </div>
    <div>
        <a href="{% url 'utakais:download_eisou_file' pk=event.pk file_type='eisou_doc' %}">Download document</a>
        <a href="{% url 'utakais:download_eisou_file' pk=event.pk file_type='eisou_pdf' %}">Download PDF</a>
    </div>
{% endblock %}

templates/utakais/events/participants_detail.html
{% extends 'base.html' %}
{% block head_title %}
    参加者詳細
{% endblock %}
{% block body_title %}
    <h1>
        参加者詳細
    </h1>
{% endblock %}
{% block content %}
    <div>
        <a href="{% url 'utakais:event_admin' pk=event.pk %}">歌会管理へ</a>
    </div>
    <h2>参加者情報</h2>
    {% if participant_formset.non_form_errors %}
        <div>
            <ul>
                {% for error in participant_formset.non_form_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <table border="1">
        {{ participant_formset.management_form }}
        {% for form in participant_formset %}
        <tr>
            <td>
                <p>参加者:{{ form.instance.name }}</p>
                {% if not form.instance.user %}
                    <p>連絡先: {{ form.instance.guest_contact }}</p>
                {% endif %}
            </td>
            <td>
                <p>{{ form.instance.tanka }}</p>
            </td>
            <td>
                削除{{ form.DELETE }}
                {% if form.errors %}
                    <div class="error">
                        <ul>
                            {% for error in form.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </table>
        <button type="submit">保存</button>
    </form>
{% endblock %}

templates/utakais/events/record.html
{% extends 'base.html' %}

{% block head_title %}
    <title>歌会記録</title>
{% endblock %}

{% block body_title %}
    <h1>{{ event.title }}</h1>
{% endblock %}

{% block content %}
    {% if user.is_authenticated and event.organizer and user == event.organizer %}
    <div>
        <a href="{% url 'utakais:event_admin' pk=event.pk %}">歌会管理へ</a>
    </div>
    {% endif %}
    <div>
        司会者：{{ event.organizer.name }}<br>
        開始日時：{{ event.start_time }}<br>
        場所：{{ event.location }}<br>
        コメント：{{ event.rec_desc }}
    </div>
    <div>
        <ul>
            {% if public_tanka %}
            <h3>公開詠草一覧</h3>
            {% for tanka in public_tanka %}
            <li>
                {{ tanka.content }}{{ tanka.author.name }}
            </li>
            {% endfor %}
            {% else %}
            <p>公開詠草はありません。</p>
            {% endif %}
            {% if user.is_authenticated and user.is_member and limited_tanka %}
            <h3>限定公開詠草一覧</h3>
            {% for tanka in limited_tanka %}
            <li>
                {{ tanka.content }}{{ tanka.author.name }}
            </li>
            {% endfor %}
            {% endif %}
        </ul>
    </div>
{% endblock %}